version: '2'
services:
   redis:
      image: registry.cn-hangzhou.aliyuncs.com/xylink/redis:3.2_v1
      container_name: redis
      restart: always
      networks:
         extnetwork:
            ipv4_address: 172.10.2.101
      ports:
        - 6379:6379
      volumes:
        - /app/redis/redis.conf:/etc/redis/redis.conf
      command: redis-server /etc/redis/redis.conf
networks:
   extnetwork:
      ipam:
         config:
         - subnet: 172.10.2.0/24
           gateway: 172.10.2.1
